name: CI

on:
  push:
    branches:
      - main
    tags: "*"
  pull_request:

env:
  ERT_SHOW_BACKTRACE: 1
  UV_SYSTEM_PYTHON: 1

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}${{ matrix.pandas-version && format(' (pandas {0})', matrix.pandas-version) || '' }}"
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13" ]
        pandas-version: [">3"]
        os: [ ubuntu-latest ]
        include:
          - python-version: "3.13"
            os: macos-latest
          - python-version: "3.13"
            pandas-version: ">=2,<3"
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          enable-cache: true
          prune-cache: false
          cache-dependency-glob: pyproject.toml
          python-version: "${{ matrix.python-version }}"

      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libegl1
        shell: bash

      - name: Install test dependencies
        run: |
          uv pip install ".[test]"

      - name: Pin pandas version
        if: matrix.pandas-version
        run: uv pip install "pandas${{ matrix.pandas-version }}"

      - name: "Run tests"
        run: pytest tests -n logical --durations 5 --ert-integration

      - name: "Run doctests on fmudesign"
        run: pytest ./src/semeio/fmudesign/ --doctest-modules -v
